name: louvor4_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  flutter_bloc: ^9.0.0
  equatable: ^2.0.5
  flutter_secure_storage: ^9.2.2
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.3.2
  intl: ^0.20.2

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon-512x512.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/logos/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Regular.ttf
        - asset: assets/fonts/Outfit-Medium.ttf
          weight: 500
        - asset: assets/fonts/Outfit-Bold.ttf
          weight: 700
